name: "Common Setup"
description: ""
inputs:
  github-token:
    description: ''
    default: ''
  fetch-depth:
    description: ''
    default: 1

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: ${{inputs.fetch-depth}}

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.x.x
          7.x.x
          8.x.x

    - uses: fabriciomurta/ensure-nuget-source@v1
      with:
        name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'

    - uses: actions/setup-dotnet@v4
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.github-token}}
